version: '3.9'


services:
  
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: sss
      MYSQL_DATABASE: "game" 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - applet

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - admin_panel
    networks:
      - applet

  phpmyadmn:
    image: phpmyadmin
    restart: always
    env_file:
      - gamble_rs/.env      
    ports:
      - 801:80
    networks:
      - applet
    depends_on:
      mysql:
        condition: service_healthy

  backend:
    build: ./gamble_rs
    container_name: backend
    command: ["sh", "-c", "sqlx migrate run && cargo run"]
    ports:
      - 5000:5000
    env_file:
      - gamble_rs/.env
    depends_on:
      mysql: 
        condition: service_healthy
    networks:
      - applet

  admin_panel:
    build: ./gamble_web
    container_name: admin_panel
    environment:
      - SERVER_URL=http://backend:5000
    ports:
      - '8080:8080'
    depends_on:
      - backend
    networks:
      - applet

networks:
  applet:
    driver: bridge

    


      
